---
title: "CITIES_REA"
author: "Afaf ALOUI & Mohamed EL-BADRI"
date: "2024-08-13"
output: html_document
---



```{r}
library(ncdf4)
library(SPEI)
library(tidyverse)
library(readODS)
# library(raster)

# Define city coordinates
cities <- data.frame(
  city = c("Casablanca", "Rabat", "Marrakech", "Tangier", "Agadir", "Fes", 
           "Oujda", "Meknes", "Laayoune", "Dakhla", "Nador", "Tetouan", 
           "Essaouira", "Al Hoceima", "Kenitra", "Beni Mellal", "Khouribga", 
           "Safi", "El Jadida", "Taza", "Ifrane", "Ouarzazate", "Chefchaouen", 
           "Errachidia", "Mohammedia", "Settat", "Sidi Kacem", "Guelmim", 
           "Taroudant"),
  lat = c(33.5731, 34.0209, 31.6295, 35.7595, 30.4278, 34.0181, 34.6823, 33.8965, 
          27.1253, 23.6847, 35.1688, 35.5785, 31.5085, 35.2471, 34.2610, 32.3397, 
          32.8805, 32.2994, 33.2311, 34.2097, 33.5333, 30.9189, 35.1715, 31.9314, 
          33.6841, 33.0011, 34.2247, 28.9880, 30.4708),
  lon = c(-7.5898, -6.8417, -7.9811, -5.8340, -9.5981, -4.9998, -1.9006, -5.5473, 
          -13.1625, -15.9579, -2.9335, -5.3684, -9.7595, -3.9315, -6.5708, -6.3498, 
          -6.9066, -9.2372, -8.5007, -3.9986, -5.1167, -6.8931, -5.2632, -4.4243, 
          -7.3827, -7.6166, -5.7074, -10.0572, -8.8769)
)

# Initialize a list to store data frames
data_list <- list()

# Open the NetCDF file to get lon and lat only once
MOROCCO_NC <- "~/SI/reanalysis_DATA/ERA5_DATA/adaptor.mars.internal-1721236535.1379626-2542-10-a274acb6-489e-428c-8fe1-c97bb6244621/data.nc"
# Open the NetCDF file to get lon and lat only once
INFILE <- nc_open(MOROCCO_NC)
LON <- ncvar_get(INFILE, "longitude")
LAT <- ncvar_get(INFILE, "latitude")
TIME=  ncvar_get(INFILE,"time")
TIME=TIME/24
TIME=as.Date(TIME,origin="1900-01-01")
nc_close(INFILE)

# Loop through each city and extract data
for (city in 1:nrow(cities)) {
  i <- which.min(abs(cities$lon[city]-LON))
  j <- which.max(abs(cities$lat[city]-LAT))
  
  # Open the NetCDF files for each variable
    INFILE <- nc_open(MOROCCO_NC)
    
    T2M <- ncvar_get(INFILE, "t2m", start = c(i, j,1, 1), count = c(1, 1,1, -1))

    RR <- ncvar_get(INFILE, "tp", start = c(i, j,1, 1), count = c(1, 1,1, -1))

    nc_close(INFILE)

    if(any(!all(is.na(RR)), !all(is.na(T2M)))) {
    
    RR=RR*24*30*1000 # convert RR from m/hour to mm/month
    T2M=T2M-273.15
    
    SPI_1=spi(RR,scale=1,na.rm = TRUE)
    SPI_3=spi(RR,scale=3,na.rm = TRUE)
    SPI_6=spi(RR,scale=6,na.rm = TRUE)
    SPI_9=spi(RR,scale=9,na.rm = TRUE)
    SPI_12=spi(RR,scale=12,na.rm = TRUE)
    
    # Convert TMAX to a data frame
    PET=thornthwaite(Tave=T2M ,lat = LAT[j], na.rm = TRUE)
    DD=RR-as.vector(PET)
    
    SPEI_1=spei(DD,scale=1,na.rm = TRUE)
    SPEI_3=spei(DD,scale=3,na.rm = TRUE)
    SPEI_6=spei(DD,scale=6,na.rm = TRUE)
    SPEI_9=spei(DD,scale=9,na.rm = TRUE)
    SPEI_12=spei(DD,scale=12,na.rm = TRUE)
  
    DF <- data.frame(as.character(TIME),RR = RR,T=T2M,DD=DD,LON=LON[i],LAT=LAT[j],SPI_1$fitted,SPI_3$fitted,SPI_6$fitted,SPI_9$fitted,SPI_12$fitted,SPEI_1$fitted,SPEI_3$fitted,SPEI_6$fitted,SPEI_9$fitted,SPEI_12$fitted)
    colnames(DF) <- c("TIME","RR","T","DD","LON","LAT","SPI.1","SPI.3","SPI.6","SPI.9","SPI.12","SPEI.1","SPEI.3","SPEI.6","SPEI.9","SPEI.12")
    

  data_list[[cities$city[city]]] <- DF
    }
}

# Write each city's data to a separate sheet in an ODS file
write_ods(data_list, path = "CITIES_REA.ods")

```

```{r}
MOROCCO_NC <- "~/SI/reanalysis_DATA/ERA5_DATA/adaptor.mars.internal-1721236535.1379626-2542-10-a274acb6-489e-428c-8fe1-c97bb6244621/data.nc"
# Open the NetCDF file to get lon and lat only once
INFILE <- nc_open(MOROCCO_NC)
LON <- ncvar_get(INFILE, "longitude")
LAT <- ncvar_get(INFILE, "latitude")
TIME=  ncvar_get(INFILE,"time")
TIME=TIME/24
TIME=as.Date(TIME,origin="1900-01-01")
nc_close(INFILE)
```

```{r}
x=10;y=15
which.min(abs(x-LON))
```

